title: COVID-19 cases in charts
description: Interactive time series charts. Global COVID-19 cases followed by regions with highest number of confirmed cases.
tags: [coronavirus covid19 covid-19 update charts visualization timeseries data plotly hopkins cases]
# Google Analytics
google_analytics: UA-161341347-1
google_site_verification: C7OtmpihlobLAt4XdOw8seKHz_7g-Ls0JzGUtVnDoQU
plugins:
  - jekyll-sitemap
